### ISSUE TITLE
Exclusion rules for Nextcloud-Recognize module incomplete

### ISSUE THREAD

**Issue by browsingman** [coreruleset/nextcloud-rule-exclusions-plugin#100]
Exclusions rules for Nextcloud-Recognize Rule is not working correctly.
The recognise Modul allows renaming Photos to names instead of numbers.

The current rule works correctly if they are only addressed by numbers, but as soon as it is renamed to Names, the exclusion rule does not apply any more and the request is being blocked.

**Comment by EsadCetiner** [comment]
@browsingman I'm not sure if you mean something else, but do you mean renaming tagged faces within the photos app? That's the only false positive I can find relating to Photos and Recognize. If your having issues with something else could you provide detailed instructions on how to reproduce it or share your modsec audit log?

**Comment by browsingman** [comment]
Yes sorry. I was a bit tired when writing this and English is not my native language. Of course I meant the topic if renaming tagged faces within the photos app. Do you already know what kind of fix could be used or when it will be fixed?

**Comment by EsadCetiner** [comment]
@browsingman Thanks for confirming, I prepared an PR earlier and I've just opened it now #102 

Let me know if it fixes your issue

**Comment by browsingman** [comment]
So I applied the fix that you created manually and it does indeed fix the problem ... making me very happy ;-)

**Comment by EsadCetiner** [comment]
@browsingman Good to hear your issue has been resolved. There should be a new version of the plugin `1.3.0` in a few days.
