### ISSUE TITLE
Lots of FPs with NextCloud `autosaveContent`

### ISSUE THREAD

**Issue by Xhoenix** [coreruleset/nextcloud-rule-exclusions-plugin#16]
This is the exclusion rule I'm currently using for my NextCloud Installation:-
```
SecRule REQUEST_URI "@beginsWith /apps/text/session/sync" \
    "id:1219,\
    phase:1,\
    pass,\
    t:none,\
    nolog,\
    ver:'nextcloud-rule-exclusions-plugin/1.0.0',\
    ctl:ruleRemoveTargetById=931130;ARGS:autosaveContent,\
    ctl:ruleRemoveTargetById=932200;ARGS:autosaveContent,\
    ctl:ruleRemoveTargetById=942150;ARGS:autosaveContent,\
    ctl:ruleRemoveTargetById=942410;ARGS:autosaveContent,\
    ctl:ruleRemoveTargetById=942430;ARGS:autosaveContent,\
    ctl:ruleRemoveTargetById=942440;ARGS:autosaveContent,\
    ctl:ruleRemoveTargetById=942431;ARGS:autosaveContent,\
    ctl:ruleRemoveTargetById=942460;ARGS:autosaveContent,\
    ctl:ruleRemoveTargetById=941340;ARGS:autosaveContent,\
    ctl:ruleRemoveTargetById=942550;ARGS:autosaveContent,\
    ctl:ruleRemoveTargetById=942131;ARGS:autosaveContent,\
    ctl:ruleRemoveTargetById=942200;ARGS:autosaveContent,\
    ctl:ruleRemoveTargetById=942210;ARGS:autosaveContent,\
    ctl:ruleRemoveTargetById=942300;ARGS:autosaveContent,\
    ctl:ruleRemoveTargetById=942370;ARGS:autosaveContent,\
    ctl:ruleRemoveTargetById=942380;ARGS:autosaveContent,\
    ctl:ruleRemoveTargetById=942520;ARGS:autosaveContent,\
    ctl:ruleRemoveTargetById=942490;ARGS:autosaveContent,\
    ctl:ruleRemoveTargetById=932235;ARGS:autosaveContent,\
    ctl:ruleRemoveTargetById=933120;ARGS:autosaveContent,\
    ctl:ruleRemoveTargetById=933161;ARGS:autosaveContent,\
    ctl:ruleRemoveTargetById=941330;ARGS:autosaveContent,\
    ctl:ruleRemoveTargetById=942120;ARGS:autosaveContent,\
    ctl:ruleRemoveTargetById=932236;ARGS:autosaveContent,\
    ctl:ruleRemoveTargetById=932220;ARGS:autosaveContent,\
    ctl:ruleRemoveTargetById=932160;ARGS:autosaveContent,\
    ctl:ruleRemoveTargetById=932130;ARGS:autosaveContent,\
    ctl:ruleRemoveTargetById=932125;ARGS:autosaveContent,\
    ctl:ruleRemoveTargetById=932230;ARGS:autosaveContent,\
    ctl:ruleRemoveTargetById=932115;ARGS:autosaveContent,\
    ctl:ruleRemoveTargetById=942340;ARGS:autosaveContent,\
    ctl:ruleRemoveTargetById=932370;ARGS:autosaveContent,\
    ctl:ruleRemoveTargetById=941160;ARGS:autosaveContent,\
    ctl:ruleRemoveTargetById=941320;ARGS:autosaveContent,\
    ctl:ruleRemoveTargetById=941110;ARGS:autosaveContent,\
    ctl:ruleRemoveTargetById=941390;ARGS:autosaveContent,\
    ctl:ruleRemoveTargetById=941100;ARGS:autosaveContent"
```

Although it contains few rules from PL 2. I think this needs to be taken into consideration as adding something as simple as a html tag to a text file creates a lot of FPs.

**Comment by Xhoenix** [comment]
I'm sure a lot more FPs would turn up with extended testing and either we do as I did above and add any new rule that causes FP ***or***, we can come up with a better solution for the "autosave" feature. Something similar was also reported with WordPress as can be seen in [this issue](https://github.com/coreruleset/coreruleset/issues/3000).

**Comment by theseion** [comment]
I don't know what the payload is but I presume it's either free text (like in Wordpress), including HTML, or JSON. In both cases the payload is basically arbitrary. The question is whether it even makes sense to look for things like `<script>` etc. in such content. Instead, we could just exclude the target from all CRS rules:
```
SecRule REQUEST_URI "@beginsWith /apps/text/session/sync" \
    "id:1219,\
    phase:1,\
    pass,\
    t:none,\
    nolog,\
    ver:'nextcloud-rule-exclusions-plugin/1.0.0',\
    chain"
    SecRuleUpdateTargetByTag "OWASP_CRS" !ARGS:autosaveContent
```

@azurit, what do you think?

**Comment by azurit** [comment]
I agree, it looks like it's not worth it to exclude specific rules or group of rules.

Btw, @theseion, check your rule, you cannot chain `SecRuleUpdateTargetByTag`.

**Comment by theseion** [comment]
Ups.

```
SecRule REQUEST_URI "!@beginsWith /apps/text/session/sync" \
    "id:1219,\
    phase:1,\
    pass,\
    t:none,\
    nolog,\
    ver:'nextcloud-rule-exclusions-plugin/1.0.0',\
    skip:1"

SecRuleUpdateTargetByTag "OWASP_CRS" !ARGS:autosaveContent
```

**Comment by Xhoenix** [comment]
@theseion I think `@contains` would be more appropriate. I'd have created a PR with this, but it'll require to add a new "rule-exclusions-after.conf" file. Can you fix this? I want to remove the exclusions I've added.

**Comment by theseion** [comment]
You can do that as part of your PR. Simply copy the [template-after.conf](https://github.com/coreruleset/template-plugin/blob/main/plugins/template-after.conf) template file and adapt it for this plugin.

**Comment by Xhoenix** [comment]
Hey @theseion, how do you want me to handle the `id` part. Should I pick one from the 9508100-9508999 range?

**Comment by Xhoenix** [comment]
Actually, it's not mentioned in [official docs](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-(v2.x)#secrule) whether it's mandatory to mention an `id` or not.

**Comment by Xhoenix** [comment]
Okay, Apache fails to start without an `id`

**Comment by RedXanadu** [comment]
@Xhoenix Rule IDs [are mandatory](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-(v2.x)#user-content-id).

**Comment by Xhoenix** [comment]
Yeah, I checked it after Apache failed.

**Comment by theseion** [comment]
> Hey @theseion, how do you want me to handle the `id` part. Should I pick one from the 9508100-9508999 range?

Yes. Just pick the next available number within the range for the plugin.

**Comment by Xhoenix** [comment]
I tested this without any problems in my Apache installation. But, the **plugin-lint** fails to recognize `SecRuleUpdateTargetByTag` and expects a `SecRule` instead. You can check it in [my fork](https://github.com/Xhoenix/nextcloud-rule-exclusions-plugin).

**Comment by azurit** [comment]
@theseion I don't think you can skip `SecRuleUpdateTargetByTag` using a `skip` action. Have you tested it?

`SecRuleUpdateTargetByTag` is processed AFTER all `SecRule`s by modsec engine, it works completely different than `SecRule` exclusion rules (which needs to be put before rules which you want to exclude).

**Comment by azurit** [comment]
> I tested this without any problems in my Apache installation. But, the **plugin-lint** fails to recognize `SecRuleUpdateTargetByTag` and expects a `SecRule` instead. You can check it in [my fork](https://github.com/Xhoenix/nextcloud-rule-exclusions-plugin).

That's true, see https://github.com/coreruleset/secrules_parsing/issues/43.

**Comment by theseion** [comment]
> @theseion I don't think you can skip `SecRuleUpdateTargetByTag` using a `skip` action. Have you tested it?
> 
> `SecRuleUpdateTargetByTag` is processed AFTER all `SecRule`s by modsec engine, it works completely different than `SecRule` exclusion rules (which needs to be put before rules which you want to exclude).

You're correct. Firstly, `SecRuleUpdateTargetByTag` must come _after_ any rule that should be updated by it. Secondly, `skip` only works on rules and has no effect on ``SecRuleUpdateTargetByTag`.

You could still use my proposal with the `ruleRemoveTargetByTag` action: 
```
SecRule REQUEST_URI "!@beginsWith /apps/text/session/sync" \
    "id:1219,\
    phase:1,\
    pass,\
    t:none,\
    nolog,\
    ver:'nextcloud-rule-exclusions-plugin/1.0.0',\
    ctl:ruleRemoveTargetByTag=OWASP_CRS;ARGS:autosaveContent"
```

I've tested this against ModSec 2 (Apache) and ModSec 3 (nginx).

**Comment by Xhoenix** [comment]
Seriously, `ruleRemoveTargetByTag` was my first idea. Why didn't you said so earlier? Now, I've to remove the `after.conf` file. 🙃

**Comment by theseion** [comment]
I think I looked at the docs and mistakenly thought that `ruleRemoveTargetByTag` was not supperted by libmodsecurity.

Sorry. You should always assume that I don't know everything and ask ;)

**Comment by Xhoenix** [comment]
As you contribute a lot to CRS project, I assumed you know a lot about it. 🤷‍♂️

Can you check the PR #24?

**Comment by RedXanadu** [comment]
@Xhoenix Please remember that all CRS developers are volunteers who work on this project in their spare time. There are no paid CRS developers.

This isn't paid support. You'll find lots of good advice and people willing to spend time to provide lots of help, but you won't always get perfect answers and not always fast replies or reviews. Bear in mind that people have full time jobs and personal lives to look after outside of Github :slightly_smiling_face:

**Comment by Xhoenix** [comment]
Lol, man. When did I say anything about support? I was just asking if he can check my PR which I created based upon his suggestion.

Also, I think being an official CRS developer is an award in itself. Just think of the boost it gives to one's profile and ultimately their career. And, as you said CRS devs are free to contribute _whenever_ they've spare time, I think it's like having the best of both worlds. 👻

**Comment by theseion** [comment]
Done.
