### ISSUE TITLE
FP when uploading from Android client

### ISSUE THREAD

**Issue by mhastu** [coreruleset/nextcloud-rule-exclusions-plugin#44]
The REQUEST_BODY of uploaded files from the Android client is analyzed, which leads to false positives. I tried adding `ctl:ruleRemoveTargetById=921110;REQUEST_BODY` to rule `9508174`, which did not fix the issue.

Relevant log:

``
ModSecurity: Warning. Pattern match "(?:get|post|head|options|connect|put|delete|trace|track|patch|propfind|propatch|mkcol|copy|move|lock|unlock)\\\\s+(?:\\\\/|\\\\w)[^\\\\s]*(?:\\\\s+http\\\\/\\\\d|[\\\\r\\\\n])" at REQUEST_BODY. [file "/etc/modsecurity/crs/rules/REQUEST-921-PROTOCOL-ATTACK.conf"] [line "53"] [id "921110"] [msg "HTTP Request Smuggling Attack"] [data "Matched Data: [raw data] found within REQUEST_BODY: [raw data]..."] [severity "CRITICAL"] [ver "OWASP_CRS/3.3.5"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-protocol"] [tag "paranoia-level/1"] [ [hostname "example.org"] [uri "/remote.php/dav/uploads/user/[...]"] [unique_id "[...]"]
``

**Comment by EsadCetiner** [comment]
@mhastu could you share the uri path after ``user/``, feel free to redact any sensitive information

9508174 expects the uri to end in numbers, and if it doesn't then the exclusions won't match

**Comment by mhastu** [comment]
Wow, thanks for the fast reply.
`/remote.php/dav/uploads/user/2129df88a53dba8a996390c474fc470f/000019`.
The uri in the logs seems to always have this pattern of 32 hex numbers, a slash and 6 numerals.

**Comment by EsadCetiner** [comment]
thank you, that's what I was suspecting

this PR should fix your issue https://github.com/coreruleset/nextcloud-rule-exclusions-plugin/pull/45
