### ISSUE TITLE
Nextcloud 25 False Positives

### ISSUE THREAD

**Issue by AlroneRhyn** [coreruleset/nextcloud-rule-exclusions-plugin#6]
Hello CRS Team makers!

I tried to setup a calendar+contact+webauthn only 25.0.1  Nextcloud server with ModSecurity paranoia level 2 and encountered  some false positive that i would like to share with you.

- Pretty URLs.
I guess every `SecRule REQUEST_FILENAME "@contains /index.php/$CONTROLLER` should be rewritten SecRule REQUEST_FILENAME "@contains /$CONTROLLER" especially cause it concerns passwords endpoint :o: `/login` and `/settings`

- Address-book and calendar deletion&restoration are done through **DELETE** and **MOVE** methods:
From:
```
# Allow modifying contacts via the web interface
SecRule REQUEST_METHOD "@streq PUT" \
    "id:9003321,\
    phase:1,\
    pass,\
    t:none,\
    nolog,\
    chain"
    SecRule REQUEST_FILENAME "@contains /remote.php/dav/addressbooks/" \
        "t:none,\
        ctl:ruleRemoveById=200002"
```
to:
```
SecRule REQUEST_METHOD "@rx (PUT|DELETE|MOVE)" \
    "id:9003321,\
    phase:1,\
    pass,\
    t:none,\
    nolog,\
    chain"
    SecRule REQUEST_FILENAME "@contains /remote.php/dav/addressbooks/" \
        "t:none,\
        ctl:ruleRemoveById=200002"
```
Same thing with the `/remote.php/dav/calendars/`URI.

- App theming requires a PUT method to do it's job:
```
SecRule REQUEST_FILENAME "@rx /ocs/v[0-9]+\.php/apps/theming" \
    "id:XXXXX,\
    phase:2,\
    pass,\
    t:none,\
    nolog,\
    setvar:'tx.allowed_methods=%{tx.allowed_methods} PUT'"
```

- Calendar appointment feature requires DELETE and PUT methods  to delete and edit:
```
SecRule REQUEST_FILENAME "@contains /apps/calendar/v1/appointment_configs/" \
    "id:XXXXX,\
    phase:2,\
    pass,\
    t:none,\
    nolog,\
    setvar:'tx.allowed_methods=%{tx.allowed_methods} DELETE PUT'"
```

- Recently contacted contact picture returns 501 instead of 404 ( 🤷 )
```
SecRule RESPONSE_STATUS "@streq 501" \
    "id:XXXXX,\
    phase:4,\
    pass,\
    t:none,\
    nolog,\
    chain" \
    SecRule REQUEST_FILENAME "@contains z-app-generated--contactsinteraction--recent" \
        "t:none,\
        ctl:ruleRemoveById=950100"
```

When search field is looking into the recent contact list, it will trigger an SQL injection error due to...the uri name (see above):
The following rule should be covered by the Nextcloud exclude rule `id:9003125` but URI and ARGS changed between NC20 and NC25.
```
SecRule REQUEST_FILENAME "@contains /ocs/v[0-9]+\.php/search/providers" \
    "id:XXXXX,\
    phase:2,\
    pass,\
    t:none,\
    nolog,\
    ctl:ruleRemoveTargetById=920230;ARGS:from,\
    ctl:ruleRemoveTargetByTag=attack-sqli;ARGS:from,\
    ctl:ruleRemoveTargetByTag=attack-sqli;ARGS:term"
```

- Webauthn Plugin triggers up to 5 attack-sqli rules while registering, adding and removing a physical token over 3 URLs (`/settings/api/personal/webauthn/registration`, `/apps/twofactor_webauthn/settings/finishregister` and `/login/challenge/webauthn`).
I overdone it but this way i know i won't break my auth.
```
SecRule REQUEST_FILENAME "@contains webauthn" \
    "id:XXXXX,\
    phase:2,\
    pass,\
    t:none,\
    nolog,\
    ctl:ruleRemoveTargetByTag=attack-sqli;ARGS:json.data,\
    ctl:ruleRemoveTargetByTag=attack-sqli;ARGS:challenge"
```

Same topic, removing a webauthn key requires the DELETE Method:
```
SecRule REQUEST_FILENAME "@contains /settings/api/personal/webauthn" \
    "id:XXXXX,\
    phase:2,\
    pass,\
    t:none,\
    nolog,\
    setvar:'tx.allowed_methods=%{tx.allowed_methods} DELETE'"
```

- Removing an app password requires **DELETE** method on `/settings/personal/authtokens` URI:
```
SecRule REQUEST_FILENAME "@contains /settings/personal/authtokens" \
    "id:XXXXX,\
    phase:2,\
    pass,\
    t:none,\
    nolog,\
    setvar:'tx.allowed_methods=%{tx.allowed_methods} DELETE'"
```

- Nextcloud is full of multiple input fields like appointment name and description or Webauthn security key name which are sensible to attack-sqli, i don't know if it must be excluded.
```
SecRule REQUEST_FILENAME "@contains /apps/calendar/v1/appointment_configs/" \
    "id:XXXXX,\
    phase:2,\
    pass,\
    t:none,\
    nolog,\
    ctl:ruleRemoveTargetByID=932200;ARGS:json.description,\
    ctl:ruleRemoveTargetByTag=attack-sqli;ARGS:json.description,\
```

I am kinda noob regarding ModSecurity and OWASP, please let me know if i did it wrong or if you need more data.

Regards!

**Comment by azurit** [comment]
Hi @AlroneRhyn, we have done lots or work past months. Can you test if these are still a problem? Thank you.

**Comment by theseion** [comment]
@EsadCetiner in case you're looking for something to do... ;)

**Comment by EsadCetiner** [comment]
@AlroneRhyn This PR should fix all of the issues you reported https://github.com/coreruleset/nextcloud-rule-exclusions-plugin/pull/37
Please let me know if I missed anything or if your still having issues with FPs
