### ISSUE TITLE
Nextcloud: calDAV: false positive

### ISSUE THREAD

**Issue by YeapGuy** [coreruleset/nextcloud-rule-exclusions-plugin#63]
### Description

An iPhone trying to PUT to Nextcloud's calDAV service will be blocked by CRS.

### Logs

```
[error] 97548#97548: *156197 [client xxx] ModSecurity: Access denied with code 403 (phase 2). Matched "Operator `Ge' with parameter `5' against variable `TX:BLOCKING_INBOUND_ANOMALY_SCORE' (Value: `5' ) [file "/usr/local/nginx/conf/conf.d/include/coreruleset/rules/REQUEST-949-BLOCKING-EVALUATION.conf"] [line "176"] [id "949110"] [rev ""] [msg "Inbound Anomaly Score Exceeded (Total Score: 5)"] [data ""] [severity "0"] [ver "OWASP_CRS/4.0.0"] [maturity "0"] [accuracy "0"] [tag "anomaly-evaluation"] [hostname "xxx"] [uri "/remote.php/caldav/calendars/xxx/xxx/xxx.ics"] [unique_id "171045623486.423063"] [ref ""], client: xxx, server: xxx, request: "PUT /remote.php/caldav/calendars/xxx/xxx/xxx.ics HTTP/1.1", host: "xxx"
```

### Your Environment

* CRS version (e.g., v3.3.4): 4.0.0
* Paranoia level setting (e.g. PL1) : PL1
* ModSecurity version (e.g., 2.9.6):
* Web Server and version or cloud provider / CDN (e.g., Apache httpd 2.4.54): Nginx-Proxy-Manager Plus latest
* Operating System and version: Dockerized

### Confirmation

[ ] I have removed any personal data (email addresses, IP addresses,
    passwords, domain names) from any logs posted.

**Comment by EsadCetiner** [comment]
@YeapGuy I just noticed that the log you've provided is incomplete, it only shows the [anomoly scoring rule](https://coreruleset.org/docs/concepts/anomaly_scoring/) and not the rules that led to an anomoly score of 5. ModSecurity on Nginx doesn't log the rules that led to an anomoly score of 5 by default to the error log. you'll have to either [enable info level error logging in nginx](https://nginx.org/en/docs/ngx_core_module.html#error_log) or search your modsecurity audit log (usually /var/log/modsec_audit.log) using this ID ```171045623486.423063```.

**Comment by EsadCetiner** [comment]
@YeapGuy could you give this PR a try https://github.com/coreruleset/nextcloud-rule-exclusions-plugin/pull/66? I didn't encounter the specific false positive you reported, so I can't guarantee that issue is fixed unless you provide me with more detailed logging or more detailed steps to reproduce.

**Comment by YeapGuy** [comment]
I don't use an iPhone myself, so I can't verify it myself, but so far, it seems to work. Thank you!
If it doesn't work, I'll search for the relevant modsec audit log entry as well, of course.

**Comment by YeapGuy** [comment]
Found it. It's due to content-type. Calendar invitations use `text/calendar` ([rfc](https://www.rfc-editor.org/rfc/rfc6047.txt))

**Comment by EsadCetiner** [comment]
@YeapGuy Thanks, I've pushed another commit.
